-- Supabase Migration Schema
-- Run this in the Supabase Dashboard SQL Editor

-- 1. Employees Table
CREATE TABLE IF NOT EXISTS public.employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  avatar TEXT,
  face_data TEXT,
  status TEXT DEFAULT 'Offline',
  latitude REAL DEFAULT 0.0,
  longitude REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  check_in TEXT,
  check_out TEXT,
  working_hours REAL DEFAULT 0,
  break_duration REAL DEFAULT 0,
  overtime REAL DEFAULT 0,
  status TEXT
);

-- 3. Logs Table
CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT REFERENCES public.employees(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  location TEXT,
  details TEXT
);

-- 4. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 5. Office Geofence Table
CREATE TABLE IF NOT EXISTS public.office_geofence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_name TEXT NOT NULL,
  polygon_coordinates JSONB NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default Geo-Settings Seed
INSERT INTO public.settings (key, value) VALUES 
('geofence_lat', '28.6139'),
('geofence_lng', '77.2090'),
('geofence_radius', '100')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Realtime Configuration
-- By default, Realtime is disabled on tables for security.
-- We must enable it for the tables we want to stream to the dashboard.
alter publication supabase_realtime add table public.logs;
alter publication supabase_realtime add table public.attendance;
alter publication supabase_realtime add table public.employees;

-- Row Level Security (RLS)
-- We use Service Role Key in the backend so it will bypass these by default,
-- but if we connect via frontend anon key, we'd need policies.
-- Let's turn RLS on just in case, but allow service_role everything.
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service Role Full Access" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON public.attendance FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON public.logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON public.settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON public.office_geofence FOR ALL USING (true) WITH CHECK (true);
