import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAuth, supabase } from '../context/AuthContext.jsx';
import { Shield, Key, Mail, AlertTriangle, Copy, CheckCircle } from 'lucide-react';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [dbDiagnostic, setDbDiagnostic] = useState(null); // { type: 'RLS' | 'MISSING_TABLES' | 'OTHER', message: string }
  const [copied, setCopied] = useState(false);

  // Automatic Database Connectivity Diagnostic on Mount
  useEffect(() => {
    const runRLSDiagnostic = async () => {
      try {
        const { error } = await supabase.from('settings').select('key').limit(1);
        if (error) {
          console.error('[DATABASE MOUNT DIAGNOSTIC]:', error);
          const lowerMsg = error.message.toLowerCase();
          if (lowerMsg.includes('does not exist') || error.code === '42P01') {
            setDbDiagnostic({ type: 'MISSING_TABLES', message: error.message });
          } else if (
            lowerMsg.includes('permission denied') || 
            lowerMsg.includes('row-level security') || 
            lowerMsg.includes('violates') || 
            lowerMsg.includes('rls') ||
            error.code === '42501'
          ) {
            setDbDiagnostic({ type: 'RLS', message: error.message });
          } else {
            setDbDiagnostic({ type: 'OTHER', message: error.message });
          }
        }
      } catch (err) {
        console.error('[RLS CONNECTIVITY DIAGNOSTIC EXCEPTION]:', err);
        setDbDiagnostic({ type: 'OTHER', message: err.message || String(err) });
      }
    };
    runRLSDiagnostic();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);

    const result = await login(email, password);
    if (result.success) {
      navigate('/dashboard');
    } else {
      let friendlyError = result.message || 'Authentication failed. Please verify credentials.';
      const lowerErr = friendlyError.toLowerCase();
      if (lowerErr.includes('permission denied') || lowerErr.includes('row-level security') || lowerErr.includes('violates') || lowerErr.includes('rls')) {
        setError('DATABASE_RLS_BLOCKED');
      } else {
        setError(friendlyError);
      }
      setSubmitting(false);
    }
  };

  const schemaSql = `-- 1. CREATE ALL TABLES
CREATE TABLE IF NOT EXISTS public.employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  avatar TEXT,
  face_data TEXT,
  status TEXT DEFAULT 'Offline',
  latitude REAL DEFAULT 0.0,
  longitude REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  check_in TEXT,
  check_out TEXT,
  working_hours REAL DEFAULT 0,
  break_duration REAL DEFAULT 0,
  overtime REAL DEFAULT 0,
  status TEXT
);

CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT REFERENCES public.employees(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  location TEXT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.office_geofence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_name TEXT NOT NULL,
  polygon_coordinates JSONB NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SEED DEFAULT SETTINGS
INSERT INTO public.settings (key, value) VALUES 
('geofence_lat', '28.6139'),
('geofence_lng', '77.2090'),
('geofence_radius', '100')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 3. DISABLE RLS ON ALL TABLES FOR PORTABILITY
ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

-- 4. GRANT EXPLICIT POSTGRESQL PRIVILEGES TO ALL CLIENT ROLES
GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const rlsSql = `-- Execute this in Supabase SQL Editor to grant explicit privileges and disable RLS
ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const handleCopy = (code) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="font-mono text-slate-300"
    >
      <h2 className="text-sm font-bold text-white text-center font-mono tracking-widest mb-6 uppercase text-glow-cyan">
        // SECURE GATEWAY AUTHORIZATION
      </h2>

      {/* Interactive Supabase Diagnostic Center */}
      {dbDiagnostic && (
        <div className="mb-6 p-4 bg-amber-500/5 border border-amber-500/20 rounded-2xl text-amber-200/90 text-xs font-mono leading-relaxed shadow-[0_0_15px_rgba(245,158,11,0.05)]">
          {dbDiagnostic.type === 'MISSING_TABLES' && (
            <>
              <div className="flex items-center gap-2 text-amber-400 font-bold tracking-wider uppercase mb-2">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                DATABASE SCHEMATICS MISSING
              </div>
              <p className="mb-3 text-[10px] text-slate-400">
                Supabase instance connected, but core ledger structures are absent. Run database initialization scripts.
              </p>
              <div className="bg-slate-950/70 p-3 rounded-xl border border-white/5 font-mono text-[9px] text-amber-300/80 overflow-x-auto max-h-32 mb-3 select-all">
                {schemaSql}
              </div>
              <p className="mb-3 text-[10px] text-slate-400">
                ➡️ Copy SQL block above & execute in Supabase SQL editor workspace.
              </p>
              <button
                type="button"
                onClick={() => handleCopy(schemaSql)}
                className="w-full py-2.5 bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/30 rounded-xl text-amber-300 font-bold uppercase tracking-wider text-[9px] transition-all duration-300 cursor-pointer flex items-center justify-center gap-2"
              >
                {copied ? <CheckCircle className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'COPIED TO CLIPBOARD' : 'COPY SCHEMATICS SQL'}
              </button>
            </>
          )}

          {dbDiagnostic.type === 'RLS' && (
            <>
              <div className="flex items-center gap-2 text-amber-400 font-bold tracking-wider uppercase mb-2">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                SECURITY BYPASS REQUIRED (RLS)
              </div>
              <p className="mb-3 text-[10px] text-slate-400">
                Supabase tables detected. Disable Row Level Security (RLS) policies to allow client-side sync.
              </p>
              <div className="bg-slate-950/70 p-3 rounded-xl border border-white/5 font-mono text-[9px] text-amber-300/80 overflow-x-auto max-h-32 mb-3 select-all">
                {rlsSql}
              </div>
              <p className="mb-3 text-[10px] text-slate-400">
                ➡️ Copy SQL block above & execute in Supabase SQL editor workspace.
              </p>
              <button
                type="button"
                onClick={() => handleCopy(rlsSql)}
                className="w-full py-2.5 bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/30 rounded-xl text-amber-300 font-bold uppercase tracking-wider text-[9px] transition-all duration-300 cursor-pointer flex items-center justify-center gap-2"
              >
                {copied ? <CheckCircle className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'COPIED TO CLIPBOARD' : 'COPY BYPASS SQL'}
              </button>
            </>
          )}

          {dbDiagnostic.type === 'OTHER' && (
            <>
              <div className="flex items-center gap-2 text-rose-400 font-bold tracking-wider uppercase mb-2">
                <AlertTriangle className="w-4.5 h-4.5 shrink-0" />
                ENDPOINT HANDSHAKE FAILURE
              </div>
              <p className="mb-2 text-[10px] text-slate-400">
                API connection terminated:
              </p>
              <div className="bg-slate-950/70 p-3 rounded-xl border border-rose-500/20 font-mono text-[10px] text-rose-400 overflow-x-auto mb-1">
                {dbDiagnostic.message}
              </div>
              <p className="text-[8px] text-slate-500 leading-normal mt-2">
                VERIFY LOCAL ENVIRONMENT DEPLOYMENT PARAMETERS (VITE_SUPABASE_URL / ANON_KEY).
              </p>
            </>
          )}
        </div>
      )}

      {/* Form Validation Errors */}
      {error && error !== 'DATABASE_RLS_BLOCKED' && (
        <div className="mb-4 p-3.5 bg-cyber-red/5 border border-cyber-red/20 rounded-xl text-cyber-red flex items-start gap-2.5 text-xs font-mono shadow-[0_0_15px_rgba(239,68,68,0.05)]">
          <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5 animate-pulse" />
          <span>{error}</span>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-[9px] font-bold tracking-widest text-slate-500 uppercase mb-2">Corporate Identity (Email)</label>
          <div className="relative">
            <Mail className="absolute left-3.5 top-3.5 w-4 h-4 text-slate-500 transition-colors group-focus-within:text-cyber-cyan" />
            <input
              type="email"
              required
              placeholder="e.g. employee@company.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full bg-slate-950/40 border border-white/5 focus:border-cyber-cyan focus:ring-1 focus:ring-cyber-cyan rounded-xl pl-11 pr-4 py-3.5 text-xs text-slate-200 placeholder-slate-600 outline-none transition-all duration-200 backdrop-blur-md shadow-inner"
            />
          </div>
        </div>

        <div>
          <label className="block text-[9px] font-bold tracking-widest text-slate-500 uppercase mb-2">Security Keyphrase (Password)</label>
          <div className="relative">
            <Key className="absolute left-3.5 top-3.5 w-4 h-4 text-slate-500" />
            <input
              type="password"
              required
              placeholder="••••••••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full bg-slate-950/40 border border-white/5 focus:border-cyber-cyan focus:ring-1 focus:ring-cyber-cyan rounded-xl pl-11 pr-4 py-3.5 text-xs text-slate-200 placeholder-slate-600 outline-none transition-all duration-200 backdrop-blur-md shadow-inner"
            />
          </div>
        </div>

        <button
          type="submit"
          disabled={submitting}
          className="w-full mt-4 flex items-center justify-center gap-2 bg-gradient-to-r from-cyber-blue to-cyber-cyan text-slate-950 font-bold py-3.5 px-4 rounded-xl border border-cyan-400/20 active:scale-[0.98] hover:shadow-cyan-glow transition-all duration-300 text-xs uppercase tracking-widest cursor-pointer disabled:opacity-50"
        >
          <Shield className="w-4 h-4 text-slate-950" />
          {submitting ? 'VALIDATING SIGNATURE...' : 'Establish Secure Connection'}
        </button>
      </form>

      {/* Quick Access Credentials Panel */}
      <div className="mt-6 p-4 rounded-2xl border border-white/5 bg-slate-950/20 backdrop-blur-md">
        <h3 className="text-[8px] font-bold tracking-widest text-slate-500 uppercase mb-3 text-center">// BYPASS KEYCARD SLOTS</h3>
        <div className="grid grid-cols-2 gap-2.5">
          <button
            type="button"
            onClick={() => {
              setEmail('admin@company.com');
              setPassword('adminpassword');
            }}
            className="glass-card-futuristic flex flex-col items-center justify-center p-3 rounded-xl border border-white/5 text-center cursor-pointer group"
          >
            <span className="text-[9px] font-bold text-cyber-cyan group-hover:text-cyan-300 transition-colors tracking-widest">SYS_ADMIN</span>
            <span className="text-[8px] text-slate-400 mt-1 select-none font-semibold truncate w-full px-1">admin@company.com</span>
            <span className="text-[7px] text-slate-500 select-none">pass: adminpassword</span>
          </button>
          <button
            type="button"
            onClick={() => {
              setEmail('employee@company.com');
              setPassword('employeepassword');
            }}
            className="glass-card-futuristic flex flex-col items-center justify-center p-3 rounded-xl border border-white/5 text-center cursor-pointer group"
          >
            <span className="text-[9px] font-bold text-cyber-blue group-hover:text-blue-300 transition-colors tracking-widest">EMP_CORE</span>
            <span className="text-[8px] text-slate-400 mt-1 select-none font-semibold truncate w-full px-1">employee@company.com</span>
            <span className="text-[7px] text-slate-500 select-none">pass: employeepassword</span>
          </button>
        </div>
      </div>

      <div className="mt-6 text-center">
        <p className="text-[9px] text-slate-600 uppercase tracking-widest">
          Biometric registration restricted. Contact System Operations Center.
        </p>
      </div>
    </motion.div>
  );
}
