import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth, supabase } from '../context/AuthContext.jsx';
import { Shield, Key, Mail, AlertTriangle, Copy, CheckCircle, UserRound, Eye, EyeOff, HelpCircle } from 'lucide-react';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [dbDiagnostic, setDbDiagnostic] = useState(null);
  const [copied, setCopied] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showDemoDrawer, setShowDemoDrawer] = useState(false);

  useEffect(() => {
    const runRLSDiagnostic = async () => {
      try {
        const { error } = await supabase.from('settings').select('key').limit(1);
        if (!error) return;

        const lowerMsg = error.message.toLowerCase();
        if (lowerMsg.includes('does not exist') || error.code === '42P01') {
          setDbDiagnostic({ type: 'MISSING_TABLES', message: error.message });
        } else if (
          lowerMsg.includes('permission denied') ||
          lowerMsg.includes('row-level security') ||
          lowerMsg.includes('violates') ||
          lowerMsg.includes('rls') ||
          error.code === '42501'
        ) {
          setDbDiagnostic({ type: 'RLS', message: error.message });
        } else {
          setDbDiagnostic({ type: 'OTHER', message: error.message });
        }
      } catch (err) {
        setDbDiagnostic({ type: 'OTHER', message: err.message || String(err) });
      }
    };
    runRLSDiagnostic();
  }, []);

  const schemaSql = `CREATE TABLE IF NOT EXISTS public.employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  avatar TEXT,
  face_data TEXT,
  status TEXT DEFAULT 'Offline',
  latitude REAL DEFAULT 0.0,
  longitude REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  check_in TEXT,
  check_out TEXT,
  working_hours REAL DEFAULT 0,
  break_duration REAL DEFAULT 0,
  overtime REAL DEFAULT 0,
  status TEXT
);

CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT REFERENCES public.employees(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  location TEXT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS public.settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS public.office_geofence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_name TEXT NOT NULL,
  polygon_coordinates JSONB NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.settings (key, value) VALUES
('geofence_lat', '28.6139'),
('geofence_lng', '77.2090'),
('geofence_radius', '100')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const rlsSql = `ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);

    const result = await login(email, password);
    if (result.success) {
      const cachedUser = JSON.parse(localStorage.getItem('quantum_user') || '{}');
      navigate(cachedUser.role === 'admin' ? '/dashboard' : '/employee-dashboard');
      return;
    }

    const friendlyError = result.message || 'Authentication failed. Please verify credentials.';
    const lowerErr = friendlyError.toLowerCase();
    setError(
      lowerErr.includes('permission denied') ||
      lowerErr.includes('row-level security') ||
      lowerErr.includes('violates') ||
      lowerErr.includes('rls')
        ? 'DATABASE_RLS_BLOCKED'
        : friendlyError
    );
    setSubmitting(false);
  };

  const handleCopy = (code) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const diagnosticCopy = dbDiagnostic?.type === 'MISSING_TABLES' ? schemaSql : rlsSql;

  const demoAccounts = [
    { label: 'Admin', mail: 'hr.orbitengineering.group@gmail.com', pass: 'admin@2026', dept: 'Security & HR' },
    { label: 'Employee', mail: 'employee@company.com', pass: 'employeepassword', dept: 'Engineering' }
  ];

  return (
    <div className="min-h-screen w-full relative flex flex-col items-center justify-center p-4 bg-gradient-to-tr from-[#e0f2fe] via-[#f0f9ff] to-[#f8fafc] overflow-hidden select-none font-sans">
      
      {/* Cityscape Background Layer 1 (Tall, Light) */}
      <svg className="absolute bottom-0 left-0 w-full h-[240px] pointer-events-none opacity-[0.25]" viewBox="0 0 1440 220" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none">
        <path d="M0 220 V160 H40 V120 H90 V140 H130 V90 H180 V130 H220 V80 H280 V150 H320 V110 H370 V130 H410 V70 H470 V140 H520 V110 H570 V150 H620 V95 H670 V135 H710 V60 H770 V125 H820 V105 H870 V145 H920 V85 H970 V120 H1010 V50 H1070 V135 H1120 V110 H1170 V140 H1220 V75 H1270 V125 H1310 V90 H1360 V150 H1400 V110 H1440 V220 Z" fill="url(#cityGradLight)" />
        <defs>
          <linearGradient id="cityGradLight" x1="720" y1="50" x2="720" y2="220" gradientUnits="userSpaceOnUse">
            <stop offset="0%" stopColor="#bae6fd" stopOpacity="0.45" />
            <stop offset="100%" stopColor="#bae6fd" stopOpacity="0.9" />
          </linearGradient>
        </defs>
      </svg>

      {/* Cityscape Background Layer 2 (Medium, Darker) */}
      <svg className="absolute bottom-0 left-0 w-full h-[160px] pointer-events-none opacity-[0.42]" viewBox="0 0 1440 150" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none">
        <path d="M0 150 V110 H60 V90 H110 V120 H160 V85 H210 V110 H260 V70 H310 V105 H360 V80 H410 V115 H460 V95 H510 V120 H560 V65 H610 V100 H660 V85 H710 V110 H760 V90 H810 V115 H860 V75 H910 V105 H960 V85 H1010 V110 H1060 V60 H1110 V95 H1160 V80 H1210 V115 H1260 V90 H1310 V105 H1360 V70 H1410 V100 H1440 V150 Z" fill="url(#cityGradDark)" />
        <defs>
          <linearGradient id="cityGradDark" x1="720" y1="60" x2="720" y2="150" gradientUnits="userSpaceOnUse">
            <stop offset="0%" stopColor="#7dd3fc" stopOpacity="0.55" />
            <stop offset="100%" stopColor="#38bdf8" stopOpacity="0.8" />
          </linearGradient>
        </defs>
      </svg>

      {/* Concentric Ranging Circles */}
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full border border-blue-500/[0.04] pointer-events-none"></div>
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full border border-blue-500/[0.03] pointer-events-none"></div>
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[1000px] rounded-full border border-blue-500/[0.02] pointer-events-none"></div>

      {/* Decorative Grid Dot Patterns */}
      <svg className="absolute left-[8%] top-[25%] w-24 h-48 opacity-[0.22] pointer-events-none hidden md:block text-blue-500" fill="currentColor" viewBox="0 0 100 200">
        <defs>
          <pattern id="dotPattern" x="0" y="0" width="16" height="16" patternUnits="userSpaceOnUse">
            <circle cx="2" cy="2" r="1.5" />
          </pattern>
        </defs>
        <rect width="100" height="200" fill="url(#dotPattern)" />
      </svg>
      <svg className="absolute right-[8%] top-[40%] w-24 h-48 opacity-[0.22] pointer-events-none hidden md:block text-blue-500" fill="currentColor" viewBox="0 0 100 200">
        <rect width="100" height="200" fill="url(#dotPattern)" />
      </svg>

      {/* Main Header / Branding */}
      <div className="flex flex-col items-center text-center relative z-10">
        
        {/* Futuristic Shield + Fingerprint SVG Logo */}
        <div className="mb-3 drop-shadow-md">
          <svg className="w-16 h-16 animate-pulse" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M32 4C32 4 48 8 48 18C48 32 32 54 32 54C32 54 16 32 16 18C16 8 32 4 32 4Z" stroke="url(#logoShieldGrad)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" fill="url(#logoBgGrad)" />
            <path d="M32 14C29 14 26 15.5 24.5 18C23.5 19.5 23 21.5 23 23.5C23 28 27 30 27 33" stroke="#06b6d4" strokeWidth="1.8" strokeLinecap="round" />
            <path d="M32 18C30.5 18 29 19 28 20.5C27 22 26.5 23.5 26.5 25C26.5 28.5 29.5 30 29.5 33C29.5 35 30.5 37 32 37" stroke="#3b82f6" strokeWidth="1.8" strokeLinecap="round" />
            <path d="M32 22C31.5 22 31 22.2 30.7 22.6C30.3 23 30 23.8 30 24.8C30 27.8 32 28.8 32 30.8C32 31.8 32.5 32.8 33 33.3" stroke="#1d4ed8" strokeWidth="1.8" strokeLinecap="round" />
            <path d="M37 19.5C36 17.5 34 16.5 32 16.5" stroke="#3b82f6" strokeWidth="1.8" strokeLinecap="round" />
            <path d="M37.5 24C37.5 20.5 34.5 19 32 19" stroke="#06b6d4" strokeWidth="1.8" strokeLinecap="round" />
            <path d="M39.5 28.5C39.5 25 36.5 23 34 23" stroke="#3b82f6" strokeWidth="1.8" strokeLinecap="round" />
            <defs>
              <linearGradient id="logoShieldGrad" x1="16" y1="4" x2="48" y2="54" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor="#2563eb" />
                <stop offset="100%" stopColor="#06b6d4" />
              </linearGradient>
              <linearGradient id="logoBgGrad" x1="32" y1="4" x2="32" y2="54" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor="#eff6ff" stopOpacity="0.8" />
                <stop offset="100%" stopColor="#dbeafe" stopOpacity="0.4" />
              </linearGradient>
            </defs>
          </svg>
        </div>

        <h1 className="text-3xl font-extrabold text-slate-800 tracking-tight">
          Orbit<span className="text-[#005cff] font-extrabold">Guard</span>
        </h1>

        <div className="flex items-center gap-2 mt-2 select-none">
          <div className="h-[1px] w-8 bg-blue-300"></div>
          <span className="text-xs font-semibold text-[#005cff] uppercase tracking-widest font-mono">Workforce OS</span>
          <div className="h-[1px] w-8 bg-blue-300"></div>
        </div>

        <p className="text-[11px] font-medium text-slate-400 mt-2 max-w-[270px] leading-relaxed">
          AI-powered attendance & workforce intelligence platform
        </p>
      </div>

      {/* Main Login Card container */}
      <motion.div 
        initial={{ opacity: 0, y: 15 }} 
        animate={{ opacity: 1, y: 0 }} 
        transition={{ duration: 0.4 }} 
        className="w-full max-w-[420px] bg-white rounded-3xl border border-blue-100/50 shadow-[0_20px_50px_rgba(0,92,255,0.04)] p-8 mt-6 relative z-10 overflow-hidden"
      >
        <h2 className="text-xl font-bold text-slate-800 text-center">Welcome back</h2>
        <p className="text-xs text-slate-400 text-center mt-1">Sign in to continue to your account</p>

        {/* Database diagnostics warnings if active */}
        {dbDiagnostic && (
          <div className="mt-4 p-4 bg-amber-50 border border-amber-100 rounded-2xl text-xs text-amber-800">
            <div className="flex items-start gap-2.5">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
              <div className="min-w-0 flex-1">
                <p className="font-bold">
                  {dbDiagnostic.type === 'MISSING_TABLES' ? 'Database setup missing' : dbDiagnostic.type === 'RLS' ? 'Database RLS action needed' : 'Connection diagnostic active'}
                </p>
                <p className="mt-0.5 text-[11px] opacity-85 leading-relaxed">{dbDiagnostic.message}</p>
                {dbDiagnostic.type !== 'OTHER' && (
                  <div className="mt-3">
                    <pre className="max-h-24 overflow-auto rounded-lg border border-amber-200/50 bg-white/70 p-2 text-[10px] text-slate-600 font-mono leading-relaxed">{diagnosticCopy}</pre>
                    <button type="button" onClick={() => handleCopy(diagnosticCopy)} className="mt-2 inline-flex items-center gap-1.5 rounded-lg border border-amber-200 bg-white px-2.5 py-1.5 text-[10px] font-bold text-amber-900 transition hover:bg-amber-100 cursor-pointer">
                      {copied ? <CheckCircle className="h-3 w-3 text-emerald-600" /> : <Copy className="h-3 w-3" />}
                      {copied ? 'Copied' : 'Copy Setup SQL'}
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Action errors */}
        {error && error !== 'DATABASE_RLS_BLOCKED' && (
          <div className="flex items-start gap-2 rounded-xl border border-rose-100 bg-rose-50 p-3 text-xs text-rose-700 mt-4 leading-relaxed">
            <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-rose-600" />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4.5 mt-5">
          {/* Employee ID or Admin Email Field */}
          <div>
            <label className="block text-[10px] font-extrabold text-slate-500 uppercase tracking-wider mb-1.5">Employee ID / Admin Email</label>
            <div className="relative flex items-center">
              <span className="absolute left-3.5 text-slate-400 flex items-center pointer-events-none pr-3 border-r border-slate-100">
                {/* <Mail className="h-4 w-4" /> */}
              </span>
              <input 
                type="text" 
                required 
                placeholder="e.g. OES/038 or admin@company.com" 
                value={email} 
                onChange={(e) => setEmail(e.target.value)} 
                className="w-full pl-[52px] pr-4 py-3 bg-white border border-slate-200 rounded-xl text-sm focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 placeholder-slate-350 transition-all outline-none text-slate-800" 
              />
            </div>
          </div>

          {/* Password Field */}
          <div>
            <label className="block text-[10px] font-extrabold text-slate-500 uppercase tracking-wider mb-1.5">Password</label>
            <div className="relative flex items-center">
              <span className="absolute left-3.5 text-slate-400 flex items-center pointer-events-none pr-3 border-r border-slate-100">
                {/* <Key className="h-4 w-4" /> */}
              </span>
              <input 
                type={showPassword ? "text" : "password"} 
                required 
                placeholder="Enter your password" 
                value={password} 
                onChange={(e) => setPassword(e.target.value)} 
                className="w-full pl-[52px] pr-11 py-3 bg-white border border-slate-200 rounded-xl text-sm focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 placeholder-slate-350 transition-all outline-none text-slate-800" 
              />
              <button 
                type="button" 
                onClick={() => setShowPassword(!showPassword)} 
                className="absolute right-3.5 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer"
              >
                {showPassword ? <EyeOff className="h-4.5 w-4.5" /> : <Eye className="h-4.5 w-4.5" />}
              </button>
            </div>
          </div>

          {/* Remember me & Forgot Link */}
          <div className="flex items-center justify-between text-xs mt-3">
            <label className="flex items-center gap-2 cursor-pointer select-none text-slate-500 font-medium">
              <input 
                type="checkbox" 
                className="rounded border-slate-300 text-[#005cff] focus:ring-0 cursor-pointer w-4 h-4" 
              />
              Remember me
            </label>
            <a 
              href="#forgot" 
              onClick={(e) => { e.preventDefault(); alert("Corporate Credentials Policy: Please contact your IT Department or HR manager to retrieve or reset your workforce sign-in keyphrase."); }} 
              className="text-[#005cff] hover:underline font-bold"
            >
              Forgot password?
            </a>
          </div>

          {/* Secure Sign In Button */}
          <button 
            type="submit" 
            disabled={submitting} 
            className="w-full mt-6 bg-[#005cff] hover:bg-blue-600 active:scale-[0.98] text-white text-sm font-semibold py-3 px-4 rounded-xl flex items-center justify-center gap-2 shadow-[0_8px_24px_rgba(0,92,255,0.18)] hover:shadow-[0_12px_28px_rgba(0,92,255,0.22)] active:shadow-sm transition-all cursor-pointer border border-blue-400/20"
          >
            <Shield className="h-4.5 w-4.5 text-white shrink-0" />
            {submitting ? 'Authenticating...' : 'Secure Sign In'}
          </button>
        </form>

        {/* Divider with central Shield Icon */}
        <div className="relative my-6 flex items-center justify-center select-none">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-slate-100"></div>
          </div>
          <div className="relative z-10 bg-white px-3 flex items-center justify-center">
            <div className="w-6 h-6 rounded-full bg-blue-50/50 flex items-center justify-center border border-blue-100/50">
              <Shield className="w-3 h-3 text-[#005cff]" />
            </div>
          </div>
        </div>

        {/* Centered Lock footer */}
        <div className="flex items-center justify-center gap-1.5 text-[9px] text-slate-400 font-extrabold uppercase tracking-wider select-none">
          <Key className="w-3 h-3 text-slate-350" />
          Authorized person only
        </div>
      </motion.div>

      {/* Futuristic Floating Demo Access Widgets (Slide-in Drawer) */}
      <div className="fixed bottom-6 left-6 z-50 select-none">
        <AnimatePresence>
          {showDemoDrawer && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 15 }} 
              animate={{ opacity: 1, scale: 1, y: 0 }} 
              exit={{ opacity: 0, scale: 0.95, y: 15 }} 
              className="mb-3 p-4 bg-white/95 backdrop-blur-md border border-blue-100 rounded-2xl shadow-[0_15px_40px_rgba(0,92,255,0.08)] w-[300px] overflow-hidden"
            >
              <div className="flex items-center justify-between border-b border-slate-100 pb-2 mb-3">
                <span className="text-[10px] font-extrabold tracking-widest uppercase text-slate-400 flex items-center gap-1.5">
                  <Key className="w-3.5 h-3.5 text-[#005cff]" />
                  Workforce Credentials
                </span>
                <span className="text-[9px] px-1.5 py-0.5 rounded bg-blue-50 border border-blue-100 text-[#005cff] font-bold uppercase">Demo Mode</span>
              </div>
              <div className="space-y-2">
                {demoAccounts.map(item => (
                  <button 
                    key={item.label} 
                    type="button" 
                    onClick={() => { 
                      setEmail(item.mail); 
                      setPassword(item.pass); 
                      setShowDemoDrawer(false); 
                    }} 
                    className="w-full rounded-xl border border-slate-150 bg-slate-50/50 p-2.5 text-left transition hover:border-blue-200 hover:bg-blue-50/50 flex items-center justify-between group cursor-pointer"
                  >
                    <div>
                      <span className="flex items-center gap-1.5 text-xs font-bold text-slate-800 group-hover:text-[#005cff] transition-colors">
                        <UserRound className="h-3.5 w-3.5 text-slate-400 group-hover:text-[#005cff] transition-colors" />
                        {item.label} Profile
                      </span>
                      <span className="mt-0.5 block text-[10px] text-slate-450 truncate max-w-[200px]">{item.mail}</span>
                    </div>
                    <span className="text-[9px] font-bold text-slate-400 capitalize bg-white/80 border border-slate-100 px-1.5 py-0.5 rounded shadow-sm">{item.dept.split(' ')[0]}</span>
                  </button>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <button 
          type="button" 
          onClick={() => setShowDemoDrawer(!showDemoDrawer)} 
          className="flex items-center gap-2 rounded-xl bg-white border border-blue-100 hover:border-blue-200 px-4 py-2.5 text-xs font-bold text-slate-700 hover:text-[#005cff] shadow-md hover:shadow-lg transition-all cursor-pointer relative"
        >
          <HelpCircle className="w-4 h-4 text-[#005cff]" />
          Quick Access Credentials
          <span className="absolute -top-1.5 -right-1 w-2.5 h-2.5 bg-blue-500 rounded-full animate-ping"></span>
          <span className="absolute -top-1.5 -right-1 w-2.5 h-2.5 bg-blue-500 rounded-full"></span>
        </button>
      </div>

    </div>
  );
}






























