import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAuth, supabase } from '../context/AuthContext.jsx';
import { Shield, Key, Mail, AlertTriangle, Copy, CheckCircle, UserRound } from 'lucide-react';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [dbDiagnostic, setDbDiagnostic] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const runRLSDiagnostic = async () => {
      try {
        const { error } = await supabase.from('settings').select('key').limit(1);
        if (!error) return;

        const lowerMsg = error.message.toLowerCase();
        if (lowerMsg.includes('does not exist') || error.code === '42P01') {
          setDbDiagnostic({ type: 'MISSING_TABLES', message: error.message });
        } else if (
          lowerMsg.includes('permission denied') ||
          lowerMsg.includes('row-level security') ||
          lowerMsg.includes('violates') ||
          lowerMsg.includes('rls') ||
          error.code === '42501'
        ) {
          setDbDiagnostic({ type: 'RLS', message: error.message });
        } else {
          setDbDiagnostic({ type: 'OTHER', message: error.message });
        }
      } catch (err) {
        setDbDiagnostic({ type: 'OTHER', message: err.message || String(err) });
      }
    };
    runRLSDiagnostic();
  }, []);

  const schemaSql = `CREATE TABLE IF NOT EXISTS public.employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  avatar TEXT,
  face_data TEXT,
  status TEXT DEFAULT 'Offline',
  latitude REAL DEFAULT 0.0,
  longitude REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  check_in TEXT,
  check_out TEXT,
  working_hours REAL DEFAULT 0,
  break_duration REAL DEFAULT 0,
  overtime REAL DEFAULT 0,
  status TEXT
);

CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT REFERENCES public.employees(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  location TEXT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS public.settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS public.office_geofence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_name TEXT NOT NULL,
  polygon_coordinates JSONB NOT NULL,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.settings (key, value) VALUES
('geofence_lat', '28.6139'),
('geofence_lng', '77.2090'),
('geofence_radius', '100')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const rlsSql = `ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_geofence DISABLE ROW LEVEL SECURITY;

GRANT ALL PRIVILEGES ON TABLE public.employees TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.attendance TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.logs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.office_geofence TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);

    const result = await login(email, password);
    if (result.success) {
      navigate('/dashboard');
      return;
    }

    const friendlyError = result.message || 'Authentication failed. Please verify credentials.';
    const lowerErr = friendlyError.toLowerCase();
    setError(
      lowerErr.includes('permission denied') ||
      lowerErr.includes('row-level security') ||
      lowerErr.includes('violates') ||
      lowerErr.includes('rls')
        ? 'DATABASE_RLS_BLOCKED'
        : friendlyError
    );
    setSubmitting(false);
  };

  const handleCopy = (code) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const diagnosticCopy = dbDiagnostic?.type === 'MISSING_TABLES' ? schemaSql : rlsSql;

  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }} className="space-y-6">
      <div>
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Secure access</p>
        <h2 className="mt-1 text-2xl font-semibold text-slate-900">Welcome back</h2>
        <p className="mt-1 text-sm text-slate-500">Sign in to manage attendance, biometric scans, and geofence activity.</p>
      </div>

      {dbDiagnostic && (
        <div className={`rounded-xl border p-4 text-sm ${dbDiagnostic.type === 'OTHER' ? 'bg-rose-50 border-rose-100 text-rose-700' : 'bg-amber-50 border-amber-100 text-amber-800'}`}>
          <div className="flex items-start gap-3">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <div className="min-w-0 flex-1">
              <p className="font-semibold">
                {dbDiagnostic.type === 'MISSING_TABLES' ? 'Database tables are missing' : dbDiagnostic.type === 'RLS' ? 'Database permissions need attention' : 'Connection diagnostic'}
              </p>
              <p className="mt-1 text-xs opacity-80">{dbDiagnostic.message}</p>
              {dbDiagnostic.type !== 'OTHER' && (
                <>
                  <pre className="mt-3 max-h-32 overflow-auto rounded-lg border border-current/10 bg-white/60 p-3 text-[11px] leading-relaxed text-slate-700">{diagnosticCopy}</pre>
                  <button type="button" onClick={() => handleCopy(diagnosticCopy)} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-current/20 px-3 py-2 text-xs font-semibold transition hover:bg-white/50">
                    {copied ? <CheckCircle className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                    {copied ? 'Copied' : 'Copy SQL'}
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {error && error !== 'DATABASE_RLS_BLOCKED' && (
        <div className="flex items-start gap-2 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="mb-2 block text-sm font-medium text-slate-700">Corporate email</label>
          <div className="relative">
            <Mail className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" />
            <input type="email" required placeholder="employee@company.com" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full pl-10" />
          </div>
        </div>

        <div>
          <label className="mb-2 block text-sm font-medium text-slate-700">Password</label>
          <div className="relative">
            <Key className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" />
            <input type="password" required placeholder="Enter your password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full pl-10" />
          </div>
        </div>

        <button type="submit" disabled={submitting} className="ui-button ui-button-primary w-full">
          <Shield className="h-4 w-4" />
          {submitting ? 'Signing in...' : 'Sign in'}
        </button>
      </form>

      <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-3">
        <p className="mb-3 text-center text-xs font-semibold uppercase tracking-wide text-slate-500">Demo credentials</p>
        <div className="grid grid-cols-2 gap-2">
          {[
            { label: 'Admin', mail: 'admin@company.com', pass: 'adminpassword' },
            { label: 'Employee', mail: 'employee@company.com', pass: 'employeepassword' },
          ].map((item) => (
            <button key={item.label} type="button" onClick={() => { setEmail(item.mail); setPassword(item.pass); }} className="rounded-lg border border-slate-200 bg-white p-3 text-left transition hover:border-indigo-200 hover:bg-indigo-50">
              <span className="flex items-center gap-2 text-sm font-semibold text-slate-900"><UserRound className="h-4 w-4 text-indigo-600" />{item.label}</span>
              <span className="mt-1 block truncate text-xs text-slate-500">{item.mail}</span>
            </button>
          ))}
        </div>
      </div>
    </motion.div>
  );
}
